### ISSUE TITLE
Feature: add workflow subject as relatedEntity to the JMS Job

### ISSUE THREAD

**Issue by meDavid** [GlobalTradingTechnologies/workflow-extensions-bundle#4]
In our workflow setup we have some scheduled transitions for reminders we a subject enters a certain place, but we would like to clean those scheduled jobs if the subjects leaves the place using a different (or the same, but not scheduled) transition.

For this functionality I like to use the JMS Job repository like so:
```
$jobRepository = $entityManager->getRepository(Job::class);
$relatedJobs = $jobRepository->findAllForRelatedEntity($subject);
```

The current implementation of the ActionScheduler doesn't set the related entity on the JMS Job like: 
```
$jobToSchedule->addRelatedEntity($workflowContext->getSubject());
```

Is there a specific reason that the related entity is not set or is a pull request welcome?

**Comment by fduch** [comment]
Hi @meDavid!

At the moment when scheduled job is triggered in your case subject is already in different marking that probably should not allow "scheduled" transition. In this case "scheduled" transition will simply fail once and nothing will be done. So I think basically manual clearing the job repository is redundant overkill.

Probably similar problem can occur when there is a periodical rescheduling transition (triggered by periodical event for example) that can never be applied since subject was moved by another transition to the marking from which rescheduling transition is not allowed. In such situation probably we can consider to allow disabling rescheduling externally from domain code to avoid unnecessary processing. But this case little bit differs to yours.

**Comment by meDavid** [comment]
@fduch In our usecase the subject can come back to the original place, creating a new scheduled job. Only the timing of the latest scheduled job is the correct one and as such we need to clean the other job.

While we can argue the specific usecase, isn't it reasonable to add the relatedEntity to the JMS Job, which would make job lookups easier? Or is there a beter way to find related jobs for a given subject?

**Comment by fduch** [comment]
If you schedule the transition on the workflow event triggered by entering concrete marking by the subject and after some time subject enters the same marking but originally scheduled transition hasn't been performed it should be rescheduled (update timing) by the engine. 

Please refer to https://github.com/GlobalTradingTechnologies/workflow-extensions-bundle/blob/master/Schedule/ActionScheduler.php#L77-L85

**Comment by meDavid** [comment]
@fduch I didn't notice this reschedule behaviour before, but it would indeed circumvent the duplicate scheduled jobs.

I'll close this issue and ub class the actionscheduler to add the relatedEntity
